### ISSUE TITLE
詳細画面でサイズが間違ってる

### ISSUE THREAD

**Issue by tanahaya** [tanahaya/asoviva#24]

**Comment by s11y** [comment]
これどういうこと？

**Comment by tanahaya** [comment]
下にスクロールするとすぐに戻ってしまう。これを直したい。

**Comment by s11y** [comment]
`EurekaImageCellTableViewCell.xib`のViewのサイズが小さいから大きくするのと、`CustomImage`に対してAutoLayoutつけてあげよう

**Comment by tanahaya** [comment]
直しました。

**Comment by s11y** [comment]
🎉 🎉 🎉

**Comment by s11y** [comment]
@tanahaya 治ったなら閉じようか
