### ISSUE TITLE
お店を表示する画面でFolding-cellを使いたい

### ISSUE THREAD

**Issue by tanahaya** [tanahaya/asoviva#25]

**Comment by tanahaya** [comment]
tableviewcontrollerじゃないと無理そう。

**Comment by s11y** [comment]
https://www.google.co.jp/search?q=swift+tableview+accordion&oq=swift+tableview+accordion+&aqs=chrome..69i57j0.11574j0j7&sourceid=chrome&ie=UTF-8

このあたりにないか？
アコーディオンなら`UITableView`でもできると思うぞ。
