### ISSUE TITLE
RecommendViewのお気に入り登録が出来ない。

### ISSUE THREAD

**Issue by tanahaya** [tanahaya/asoviva#27]

**Comment by s11y** [comment]
`Realm`使わないのかい？

**Comment by tanahaya** [comment]
なるほど

**Comment by s11y** [comment]
👍

**Comment by s11y** [comment]
https://github.com/tanahaya/asoviva/commit/dd419eab75fba2baf4e688e4f0df08d2ac666cae#commitcomment-22305423

**Comment by s11y** [comment]
`favoriteRealm`から`Favorite`にクラス名変えとこう
