### ISSUE TITLE
デザインを完成させる

### ISSUE THREAD

**Issue by tanahaya** [tanahaya/asoviva#31]

**Comment by s11y** [comment]
https://www.materialpalette.com/

**Comment by s11y** [comment]
https://material.io/

**Comment by s11y** [comment]
https://color.adobe.com/ja/create/color-wheel/?base=2&rule=Triad&selected=1&name=%E3%83%9E%E3%82%A4%20Color%20%E3%83%86%E3%83%BC%E3%83%9E&mode=rgb&rgbvalues=0.14626016260162597,0.21109666080790607,0.503921568627451,0.984313725490196,0.3254901960784314,0.11764705882352941,0.3137254901960784,0.4025877398670602,0.803921568627451,0.32459793916663116,0.603921568627451,0.07403828694952332,0.3665725550948145,0.503921568627451,0.24336736429327008&swatchOrder=0,1,2,3,4

**Comment by s11y** [comment]
色決めがこのへんを参考にしてみて

**Comment by tanahaya** [comment]
![Uploading Simulator Screen Shot 2017.06.18 22.14.17.png…]()
こんな感じ
