### ISSUE TITLE
ruby on railsチュートリアルで困った

### ISSUE THREAD

**Issue by tanahaya** [tanahaya/asoviva#38]
https://github.com/tanahaya/sample_app
https://ide.c9.io/tanahaya/sample-app
rails server -b $IP -p $PORTしても
Address already in use - bind(2) for "0.0.0.0" port 8080 (Errno::EADDRINUSE)出て、

ps aux | grep rails して表示されたプロセス番号に対して 
sudo kill -9 プロセス番号 しても
プロセス番号が動いて消せない。

**Comment by tanahaya** [comment]
bundle exec puma -C config/puma.rb -b tcp://127.0.0.1:3001

**Comment by s11y** [comment]
https://stackoverflow.com/questions/31039998/address-already-in-use-bind2-errnoeaddrinuse

http://qiita.com/pugiemonn/items/06aec9741c7feed0cc0e

このへん？
てか、railsを動かしたいなら、`rails s`でええで

**Comment by tanahaya** [comment]
cloud9なんでこれらしいです。

**Comment by s11y** [comment]
マジか
そういうことならOK

**Comment by s11y** [comment]
記事見てやってみた？
結果でたら教えて

**Comment by tanahaya** [comment]
下の記事は駄目でした

**Comment by tanahaya** [comment]
上の記事の二つ目の解決策でなおりました

**Comment by s11y** [comment]
Good Job
