### ISSUE TITLE
SwiftとRubyonrailsで通信する方法がいまいちわからない

### ISSUE THREAD

**Issue by tanahaya** [tanahaya/asoviva#39]
http://qiita.com/SoyaTakahashi/items/4a40aefdf13417b1857f
を試してるけどうまくいかない
alamofireがうまく動かない
```swift
Alamofire.request(posturl,method: .post, parameters: params, encoding: JSONEncoding.default, headers: [:]).responseJSON { response in
            print(response.request as Any)  // original URL request
            print(response.response as Any) // URL response
            print(response.result.value as Any)   // result of response serialization
        }
```
で
extra argument method in callとでる

**Comment by s11y** [comment]
`extra argument method in call`なら、引数おかしいね。
ちゃんと補完使った？

**Comment by tanahaya** [comment]
.postのところでエラーが出ます

**Comment by s11y** [comment]
うそ！
こっちで触った感じあってそうね

一旦コード上げてもらえる？

**Comment by tanahaya** [comment]
stockmemosのここです。
let URL = NSURL(string: "https:asoviva-server-tanahaya.c9users.io/index")
        let req = NSMutableURLRequest(url: URL! as URL)
        Alamofire.request(req , method: .post, parameters: params, encoding: .URL, headers: nil).responseJSON { (request, response, JSON, error) in
            
            println("=============request=============")
            println(request)
            println("=============response============")
            println(response)
            println("=============JSON================")
            println(JSON)
            println("=============error===============")
            println(error)
            println("=================================")
        }

**Comment by tanahaya** [comment]
↑testViewcontrollerです

**Comment by s11y** [comment]
今ビルド通ってる？

**Comment by tanahaya** [comment]
通ってないです。原因はExtra arguement 'method' in callです。
色々ググって試してるけど進展なし

**Comment by s11y** [comment]
https://github.com/tanahaya/asoviva/tree/shinoki

**Comment by tanahaya** [comment]
出来ました。
これからユーザー登録に移ります。

**Comment by s11y** [comment]
うす！
じゃあこのissue閉じといてね
