### ISSUE TITLE
ユーザー登録問題

### ISSUE THREAD

**Issue by tanahaya** [tanahaya/asoviva#40]
https://github.com/tanahaya/asovivaserverを使ってユーザー登録をしてるけど
データーベースにユーザーが登録されません。
iphone側はSignupViewControllerで処理
server側はSignup_Controllerで処理してます。

**Comment by tanahaya** [comment]
https://ide.c9.io/tanahaya/asovivaserver

**Comment by s11y** [comment]
https://github.com/tanahaya/asoviva/blob/master/asoviva/SignupViewController.swift#L64

叩いてるAPIのurl違うくない？

api/signupに送らないといけなくないか？

`routes.rb`で設定してるurlに合わせてリクエスト送らないと！
<img width="619" alt="2017-08-21 8 30 34" src="https://user-images.githubusercontent.com/11238461/29499394-0a1a3da2-864b-11e7-9bc0-e65a239fda68.png">

**Comment by tanahaya** [comment]
直しましたが
No route matches [POST]
と出ます。

**Comment by tanahaya** [comment]
Schemaのschoolをshcoolと打ち間違えてた。
エラーは変わらずNo route matches [POST]

**Comment by tanahaya** [comment]
出来た

**Comment by s11y** [comment]
ナイス
