### ISSUE TITLE
画像の投稿がよくわからない

### ISSUE THREAD

**Issue by tanahaya** [tanahaya/asoviva#45]
iphoneで選択した画像をサーバーに送ってデータベースに収納する方法がいまいちわからない。
もうちょい調べる予定。
http://blog.asobicocoro.com/entry/2016/06/22/004945
http://qiita.com/hatch/items/229df19eecdc02dc2dee

**Comment by s11y** [comment]
画像？なんの画像？

**Comment by tanahaya** [comment]
コメントと同時に画像を送れるようにしたいです。

**Comment by tanahaya** [comment]
imageをdata型にした後stringにして保存。
取り出す時はその逆をすることで取り出せるので、そうすることにしました。

**Comment by s11y** [comment]
画像をそのままjpegとかにして保存したほうがええんちゃう？
https://stackoverflow.com/questions/26335656/how-to-upload-images-to-a-server-in-ios-with-swift
